{% set version = "1.6.3" %}

{% if build_variant == "qt6" %}
{% set name = "soqt6-rt" %}
{% else %}
{% set name = "soqt-rt" %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/coin3d/soqt/releases/download/v{{ version }}/soqt-{{ version }}-src.tar.gz
    sha256: "79342e89290783457c075fb6a60088aad4a48ea072ede06fdf01985075ef46bd"
    patches:
      - patches/gl_private_linking.patch    # [linux]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - qt6-main      # [build_platform != target_platform and build_variant == "qt6"]
    - qt-main       # [build_platform != target_platform and build_variant == "qt5"]
    - ninja
    - cmake
  host:
    - qt6-main      # [build_variant == "qt6"]
    - qt-main       # [build_variant == "qt5"]
    - coin3d-rt
  run_constrained:
    - soqt-rt <0         # [build_variant == "qt6"]
    - soqt6-rt <0        # [build_variant == "qt5"]

# test:
#   requires:
#     - cmake
#     - ninja
#     - {{ compiler("cxx") }}
#     - {{ cdt('mesa-libgl-devel') }}      # [linux]
#     - {{ cdt('mesa-dri-drivers') }}      # [linux]
#
#   files:
#     - CMakeLists.txt
#
#   commands:
#     - cmake -G "Ninja" -D QT_HOST_PATH=${PREFIX} .

about:
  home: https://github.com/realthunder/coin
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: SoQt library for Coin3D with enhanced shadow rendering.
  description: >
    SoQt is a Qt GUI component toolkit library for Coin. It is also compatible with SGI and TGS Open Inventor, and the API is based on the API of the InventorXt GUI component toolkit.

extra:
  recipe-maintainers:
    - realthunder
